In [ ]:

1.Write a function to compute 5/0 and use try/except to catch the exceptions.


In [13]:
def exptArth():
    try :
        a=3
        if a < 4 : 
            b = a/(a-3) 
    except(ZeroDivisionError): 
        print("\nError Occurred and Handled")

In [14]:
exptArth()


Error Occurred and Handled


In [ ]:
2.Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] 
and verb is in ["Play", "watch"]
and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"]
Americans play Baseball. Americans play Cricket. Americans watch Baseball. Americans watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket.

In [20]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


In [29]:
for x in range(0,2):
    for j in range(len(verbs)):
        for t in range(len(objects)):
            print(subjects[x],verbs[j],objects[t])


Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [37]:
import numpy as np
x = np.array([1, 2, 3, 5])
np.vander(x)
print(np.vander(x))
print(np.vander(x, increasing=True))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [38]:
print(np.linalg.det(np.vander(x)))

48.00000000000007
